- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks: 
   - name: check number is leass than 10
     ansible.builtin.debug:
       msg: "Given number {{number}}is less than 10" 
     when: number | int < 10
   - name: check number is greater than or equal to 10
     ansible.builtin.debug:
       msg: Given number {{number}}is gretaer than or equal to 10" 
     when: number | int >= 10

   