- name: default value
  hosts: localhost
  
  tasks:
  - name: print default value
    ansible.builtin.debug:
       msg: "hello {{wishes | default('ansible')}}"

  - name: uppercase
    vars: 
     greetings: "Hello morning"
    ansible.builtin.debug:
       msg: " hello {{greetings | upper}}"

  - name: lowercase
    vars: 
     greetings: "Hello evening"
    ansible.builtin.debug:
       msg: " hello {{greetings | lower}}"
  - name: duplicate
    vars: 
     numbers: [24,2,4,3,4]
    ansible.builtin.debug:
       msg: "{{ numbers | unique }}"
  - name: min and max numbers
    vars: 
     numbers: [1,4,5,6,4,3]
    ansible.builtin.debug:
       msg: " minimum vale is {{ number | min }}and maximum number is {{number | max }}"


  