- name: variables
  hosts: local host
  vars: 
    course: "Ansible"
    Trainer: "Sivakumar"
    Duration: "120hrs"
  tasks: 
  - name: print information
    ansible.builtin.debug
     msg: "i am learning {{course}} from Trainer {{Trainer}},Duration is {{Duration}}."