- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks:
  - name: print information
    vars: #variable declaration
       course: "Devops"

    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
  - name: print information
    vars: #variable declaration
       course: "Devops"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."